version: 0.2

phases:
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean package

  post_build:
    commands:
      - echo built jar...

artifacts:
  files:
    - target/one-controller.jar
